language: cpp
compiler:
  - gcc
  - clang
before_install: sudo apt-get update -qq
install:
  - sudo add-apt-repository ppa:smspillaz/verapp-latest -y
  - sudo apt-get update
  - sudo apt-get install vera++
  - sudo apt-get install -qq libopencv-dev
before_script:
  - cd photoeffects
script:
  - cd ../itlab-vision/photoeffects
  - vera++ --error src/fadeColor.cpp
  - cd ../..
  - mkdir build
  - cd build
  - cmake ../itlab-vision/photoeffects
  - make -j5
  - cd ./bin/
  - ./photoeffects_test
notifications:
  email: false
